base_app/urls.py
from django.urls import path,include
from base_app import views

app_name = 'main'

urlpatterns = [
    path('',views.index,name='index'),
    path('signup/',views.signup,name='signup'),
    path('home/',views.homepage,name='home'),
    path('logout/',views.logout_view,name='logout_custom'),
    path('predict/',views.predict,name='predict'),
]

trade_boost/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from base_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base_app.urls')),
]

base_app/models.py
from django.db import models

# Create your models here.

base_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

base_app/views.py
from django.shortcuts import render, redirect
from .forms import NewUserForm
from django.contrib.auth import login,logout
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate

from nsepy import get_history
from datetime import date
import plotly.graph_objects as go
from plotly.offline import plot

# data = get_history(symbol="SBIN", start=date(2021,3,1), end=date.today())
# print(data.head(6))

# Create your views here.
def index(request):
    '''This is the sign-in view'''
    if request.method == 'POST':
        print(request.POST.get('password'))
        user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            return HttpResponse('Invalid User Details')
    return render(request,'index.html')

def signup(request):
    form = NewUserForm()
    if(request.method == 'POST'):
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("main:index")
        else:
            print(form.errors)
            messages.error(request, "Unsuccessful registration. Invalid information.")
            return HttpResponse(f"Unsuccessful registration. Invalid information.{form.errors}")
    else:
        return render(request,'signup.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('main:index')

def homepage(request):
    return render(request,'homepage.html')

def predict(request):
    if request.method == 'POST':
        ticker = request.POST.get('ticker')
        ticker = get_history(symbol=ticker, start=date(2021,3,1), end=date.today()) #pd df
        print(ticker.head(6))

        def candlestick():
            figure = go.Figure(
                data = [
                        go.Candlestick(
                        x = ticker.index,
                        high = ticker['High'],
                        low = ticker['Low'],
                        open = ticker['Open'],
                        close = ticker['Close'],
                        )
                    ]
            )
            candlestick_div = plot(figure, output_type='div')
            return candlestick_div

        last_candle = ticker.iloc[-1]
        buy = 0
        if(last_candle['Close']>last_candle['Open']):
            buy = 1

        
        return render(request,'homepage.html',{'candlestick':candlestick(),'ticker':request.POST.get('ticker'),'buy':buy})
        

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Trade Master</title>
</head>
<body style="background: #0f0c29;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #24243e, #302b63, #0f0c29);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #24243e, #302b63, #0f0c29); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
">
    {% block body_block%}
    {% endblock %}
</body>
</html>

templates/homepage.html
{% extends 'base.html'%}
{% block body_block %}

{% if user.is_authenticated %}
<div class = "container">
    <div class="jumbotron" style="margin-top:50px">
        <h1 class="display-3">Trade Master</h1>
        <p><b>Ai powered Stock predictions</b> </p>
        <h5>How To Use: </h5>
        <ul>
            <li>Provide the Ticker symbol - The ticker symbols as represented by NSE. </li>
            <li>Our backend will pull the lates data from NSE. </li>
            <li>Data will transformed into clean form for AI.</li>
            <li>After crunching the data AI provides the call for BUY or SELL for tommorow.</li>
        </ul>
        <hr class="my-2">
        <p>This stock predictor webapp and this by no means should be replaced by a financial advisor.</p>
        <form action="{% url 'main:predict'%}" method="post">
            {% csrf_token %}
            <input type="text" name='ticker' placeholder="Provide the Ticker Symbol">
            <button type="submit" class="btn btn-primary">Tell Position!</button>
        </form>
        <br>
        {% if candlestick %}
            <h6>Showing results for:- <b> <h5>{{ticker}}</h5> </b></h6>
            {{candlestick|safe}}
            <br>
            {% if buy %}
            <h4>Prediction for tommorow - <button type="button" class="btn btn-success">Buy</button> </h4>
            {% else %}
            <h4>Prediction for tommorow - <button type="button" class="btn btn-danger">Sell</button> </h4>
            {% endif %}
        {% endif %}
        <br>
        <a class="btn btn-primary" href="{% url 'main:logout_custom'%}">Logout</a>
    </div>
</div>
{% else %}
<div class = 'container'>
    <div class="jumbotron" style="margin-top:50px">
        <h1>Please Login !</h1>
    </div>
</div>
{% endif %}
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'base_app/css/index.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <title>Trade Master</title>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
          <h2 class="active"> Sign In </h2>
          <h2 class="inactive underlineHover">Sign Up </h2>
      
          <!-- Icon -->
          <div class="fadeIn first">
            <i class="ri-login-box-fill"></i>
            <!-- <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" /> -->
          </div>
      
          <!-- Login Form -->
          <form>
            <input type="text" id="login" class="fadeIn second" name="login" placeholder="login">
            <input type="text" id="password" class="fadeIn third" name="login" placeholder="password">
            <br>
            <input type="submit" class="fadeIn fourth" value="Log In">
          </form>
      
          <!-- Remind Passowrd -->
          <div id="formFooter">
            <a class="underlineHover" href="#">Forgot Password?</a>
          </div>
      
        </div>
      </div>
</body>
</html>

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'base_app/css/index.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <title>Trade Master</title>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
          <a href="/"><h2 class="inactive underlineHover"> Sign In </h2></a>
          <h2 class="active">Sign Up </h2>
      
          <!-- Icon -->
          <div class="fadeIn first">
            <i class="ri-login-box-fill"></i>
            <!-- <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" /> -->
          </div>
      
          <!-- Login Form -->
          <form action="{% url 'main:signup' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Sign up">
          </form>
      
          <!-- Remind Passowrd -->
          <div id="formFooter">
            <a class="underlineHover" href="#">Forgot Password?</a>
          </div>
      
        </div>
      </div>
</body>
</html>